# Site settings
#title: Globien Interlingu
title: Leeward Tan
#SEOTitle: Globien - Makes Communication Easier
SEOTitle: LeewardTan Coding Journey
#header-img: img/home-bg-bluestars.jpg
header-img: img/home-bg-bluestars.jpgw
#email: klovien@gmail.com
email: leewardtanforwork@gmail.com
description: "leeward,Ireland,code,programmer,blog"
keyword: "leeward,Ireland,code,programmer,blog"
url: "https://leewardcoder.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/LEEWARDCODER" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Leeward Personal Blog"
sidebar-avatar: ./img/leeward.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
#weibo_username:     leewardtan
zhihu_username: ni-die-die-die
github_username: LEEWARDCODER
#facebook_username:    leewardtan
jianshu_username: beb5d812d5c8
# twitter_username:   leewardtan




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: [ "less","node_modules","Gruntfile.js","package.json","README.md" ]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [ jekyll-paginate ]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f5377e02056d18c09638                            #生成的clientID
  clientSecret: cffbe78a0841fa5762febd72206f4b3394e52f84     #生成的clientSecret
  repo: LEEWARDCODER..github.io    #仓库名称
  owner: LEEWARDCODER  #github用户名
  admin: LEEWARDCODER
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: false                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接，请尽量不要删除
#friends: [
#  {
#    title: "Globien Interlingu",
#    href: "https://globien.github.io"
#  },{
#    title: "Globien Community",
#    href: "https://tieba.baidu.com/f?kw=%E6%A0%BC%E7%BD%97%E6%AF%94%E8%A8%80&fr=home"
#  },{
#    title: "Zhihu AIL Column",
#    href: "https://zhuanlan.zhihu.com/Artificial-International-Language"
#  }
#]
